name: Convert images to WebP

on:
  push:
    paths:
      - "img/payhip/**.jpg"
      - "img/payhip/**.jpeg"
      - "img/payhip/**.png"

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install WebP tools
        run: sudo apt-get install -y webp

      - name: Convert JPG/PNG to WebP
        run: |
          find img/payhip -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" \) | while read img; do
            filename="${img%.*}.webp"
            echo "Converting $img → $filename"
            cwebp -q 80 "$img" -o "$filename"
          done

      - name: Commit WebP files
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add img/payhip/**/*.webp
          git commit -m "Auto-converted images to WebP"
          git push
